# Generated by Django 4.2.23 on 2025-08-01 10:43

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=128)),
                ('timeout', models.DurationField(default=datetime.timedelta(seconds=300))),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserAuthOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('ACTIVATE_USER', 'Activate User'), ('FORGOT_PASSWORD', 'Forgot password'), ('FORGOT_PASSWORD_TOKEN', 'Forgot password token')], default='ACTIVATE_USER', max_length=64)),
                ('otp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='otp.authotp')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='userauthotp',
            constraint=models.UniqueConstraint(fields=('reason', 'user'), name='unique_reason_for_user'),
        ),
    ]
