# Generated by Django 4.2.23 on 2025-08-07 12:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authotp',
            name='timeout',
            field=models.DurationField(default=datetime.timedelta(seconds=120)),
        ),
        migrations.AlterField(
            model_name='userauthotp',
            name='reason',
            field=models.CharField(choices=[('ACTIVATE_USER', 'Activate User'), ('FORGOT_PASSWORD', 'Forgot password'), ('FORGOT_PASSWORD_TOKEN', 'Forgot password token'), ('ACTIVE_USER_PASSWORD', 'Activate user password token')], default='ACTIVATE_USER', max_length=64),
        ),
    ]
